Auth/login
21-toy-project/study_platform pull request #13
Opened 2022-04-26 08:36 UTC by JaeHee-K

2022-04-26 11:35 UTC, jiyun-Lee-dev commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private int UserNo;
사용자 아이디 int 보다 long으로 두는 건 어때?
auto increment 필드니까 계속 숫자가 늘어날 수 있을 것 같아서 
나는 post나 commentd에서 writerId를 우선 long으로 두긴 했거든
(writerId는 userId랑 헷갈릴 수 있으니까 내가 writerId -> writerNo로 변경할게)

2022-04-26 12:05 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private int UserNo;
Long

2022-04-26 12:08 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private int UserNo;
long으로 수정할게

2022-04-26 12:13 UTC, gashe-soo requested changes

2022-04-26 12:13 UTC, gashe-soo commented on build.gradle
> +//    id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
주석처리하지말고 삭제로 하자. 
그리고 작업 내역은 삭제한 이유는 적어주고

2022-04-26 12:13 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +
java naming convention 참고. 
지금 다 틀렸어.

2022-04-26 12:13 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +public class UserInfo {
굳이 User로 안한이유는?

2022-04-26 12:13 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private LocalDateTime Update_Date;
여기 두 개는 basetime entity 있지 않았어?

2022-04-26 12:13 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/service/CustomUserDetailsService.java
> +     */
java docs 이렇게 단순하게 쓰기보다는 실제로 필요한 내용을 써놓는 게 좋아

2022-04-26 12:13 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/service/UserService.java
> +    UserRepository userRepository;
Autowired Nope

2022-04-26 12:13 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/repository/UserRepository.java
> +    UserInfo findById(String ID);
variable naming 다시 확인해봐

2022-04-26 12:13 UTC, gashe-soo commented on src/main/java/toy/study_platform/config/SpringSecurityConfig.java
> +                .passwordEncoder(passwordEncoder());
code format이 이상한거 같은데 맞나?

2022-04-26 12:14 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private int UserNo;
long vs Long

2022-04-26 12:20 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private int UserNo;
long이랑 Long의 차이는 메모리 할당말고 뭔가 더 있나?

2022-04-26 12:21 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private int UserNo;
검색 ㄱㄱ

2022-05-01 04:57 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private int UserNo;
사용자 정보를 담는다는 관점에서는 null입력 여부의 차이가 큰거같네
Long이 null값을 허용하니까 Long으로 변경했어

2022-05-01 05:00 UTC, JaeHee-K commented on build.gradle
> +//    id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
ok

2022-05-01 05:02 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +public class UserInfo {
이유는 딱히 없었는데 파스칼 표기법으로 할게

2022-05-01 05:07 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +
카멜 표기법으로
UserNo > userNo
id 그대로
Pw > pw
Name > name
Auth > auth
Append_Date > appendDate
Update_Date > updateDate
Delete_Date > deleteDate
로 수정했어

2022-05-01 05:11 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +public class UserInfo {
조금 더 찾아보니 테이블명 대소문자를 windows에서는 구분하진 않지만 linux에선 구분한다고 해서 소문자로 하는게 좋다고 하네
user로 바꿀게

2022-05-01 05:20 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private LocalDateTime Update_Date;
timestamp로 받아서 처리 안하고 자동으로 바꿔주는게 있었네
UserInfo클래스에 BaseTime 상속받아서 해볼게

2022-05-01 06:13 UTC, JaeHee-K commented on src/main/java/toy/study_platform/config/SpringSecurityConfig.java
> +                .passwordEncoder(passwordEncoder());
응 이건 자동으로 탭 하나가 띄어진 상태로 입력되더라

2022-05-01 06:17 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private int UserNo;
e36ebf05f508991f5206d5e5747de1c238bae34c

2022-05-01 06:18 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +
e36ebf05f508991f5206d5e5747de1c238bae34c

2022-05-01 06:18 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +public class UserInfo {
e36ebf05f508991f5206d5e5747de1c238bae34c

2022-05-01 06:18 UTC, JaeHee-K commented on build.gradle
> +//    id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
[24f20ba](https://github.com/21-toy-project/study_platform/pull/13/commits/24f20baba4767f343754bcd466d6e717f3e9f3d2)

2022-05-01 06:19 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/service/CustomUserDetailsService.java
> +     */
java docs쓰는건 좀 더 신경써볼게 어떻게 자세하게 쓰는지를 좀 더 공부해야할 것 같네
[8d04504](https://github.com/21-toy-project/study_platform/pull/13/commits/8d045040b256a7b28c25444ec10bfb7cdffef523)

2022-05-01 06:20 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/repository/UserRepository.java
> +    UserInfo findById(String ID);
말한게 ID > id인 것 같아서 수정했어
[ac3525e](https://github.com/21-toy-project/study_platform/pull/13/commits/ac3525e0e6b6224b9014ff6ec5158328289d5e5d)

2022-05-01 06:28 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private LocalDateTime Update_Date;
지금 자료 찾아보고 있는데 BaseTime이라는 클래스(추상클래스를 쓰는 사람도 있었음)를 사용하는데 이건 패키지 구조 상 common/util안에 들어가는게 맞을까?

2022-05-01 06:29 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/service/UserService.java
> +    UserRepository userRepository;
UserRepository를 Autowired를 사용하지 않고 구현하라는거지?

2022-05-01 06:42 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +    private LocalDateTime Update_Date;
지윤이꺼 보니까 common/entity에 있네 저거를 가져가서 할게

2022-05-01 07:17 UTC, yisoo-kim commented on src/main/java/toy/study_platform/auth/service/UserService.java
> +    UserRepository userRepository;
생성자 주입

2022-05-01 12:15 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +public class UserInfo {
테이블명을 바꾸라는게 아니라 class이름을 말한거야

2022-05-01 12:16 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/service/UserService.java
> +    UserRepository userRepository;
생성자 주입

2022-05-01 12:16 UTC, gashe-soo commented on src/main/java/toy/study_platform/auth/repository/UserRepository.java
> +    UserInfo findById(String ID);
여전히 이상한데? id가 맞는건데

2022-05-01 12:16 UTC, gashe-soo commented on src/main/java/toy/study_platform/config/SpringSecurityConfig.java
> +                .passwordEncoder(passwordEncoder());
요건 아마 spotless 적용하면 될듯

2022-05-05 04:02 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/entity/UserInfo.java
> +public class UserInfo {
아 그거 CustomUserDetailsService에서 Spring Security라이브러리의 User객체를 가져다 쓰니까 이름이 중복되서 그렇게 한거야

2022-05-05 04:05 UTC, JaeHee-K commented on src/main/java/toy/study_platform/auth/repository/UserRepository.java
> +    UserInfo findById(String ID);
실수했네...
d360f10014c1fb055c3e6c725be9e1cac3de5b04

2022-05-08 09:01 UTC, closed without merging